site_name: Instrukcja BHP
site_author: Wiktor I Patryk
site_description: Instrukcja bezpieczeństwa i higieny pracy.

theme:
  name: material
  palette:
    primary: blue grey
    accent: amber

extra_css:
  - stylesheets/extra.css

nav:
  - Strona główna: index.md
  - Teoria BHP: teoria.md
  - Przykłady: przyklady.md
  - O Autorach: autorzy.md